# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-24 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('L', 'LUNES'), ('M', 'MARTES'), ('X', 'MIERCOLES'), ('J', 'JUEVES'), ('V', 'VIERNES'), ('S', 'SABADO'), ('D', 'DOMINGO')], default='L', max_length=1)),
                ('time_start', models.TimeField(default='08:00')),
                ('time_end', models.TimeField(default='17:00')),
            ],
        ),
        migrations.CreateModel(
            name='Workday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, verbose_name='Codigo')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('schedule', models.ManyToManyField(related_name='workdays', to='workdays.Schedule')),
            ],
        ),
    ]
